import type { Metadata } from "next";
import "./globals.css";

import Footer from "./components/Shared/Footer/Footer";
import Navbar from "./components/Shared/Navbar/Navbar";

export const metadata: Metadata = {
    title: "Industro",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="overflow-x-hidden scroll-smooth">
                <Navbar />
                <div className="w-[100vw-8px] overflow-hidden">{children}</div>
                <Footer />
            </body>
        </html>
    );
}
